# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colaboratory.
For use with :  https://colab.research.google.com/drive/1cBUf2Igfx9eLVbQbCoG2OulwPcdi3ARD#scrollTo=uyFD8uFYbuhU

"""

# Imports
import numpy as np
import os

from tflite_model_maker.config import ExportFormat, QuantizationConfig
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector

from tflite_support import metadata

import tensorflow as tf
assert tf.__version__.startswith('2')

# GPU Fix from https://stackoverflow.com/a/69545925
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
    # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
        print(e)


tf.get_logger().setLevel('ERROR')
from absl import logging
logging.set_verbosity(logging.ERROR)

# Confirm TF Version
print("\nTensorflow Version:")
print(tf.__version__)
print()

# Load Dataset
train_data = object_detector.DataLoader.from_pascal_voc(
    'shapes/train/images', # training images
    'shapes/train/annotations', # annotations
    ['box', 'circle', 'path', 'tree', 'x'] # class names
)

val_data = object_detector.DataLoader.from_pascal_voc(
    'shapes/validate/images', # validation images
    'shapes/validate/annotations', # validation annotations
    ['box', 'circle', 'path', 'tree', 'x'] # class names
)

# Load model spec
spec = object_detector.EfficientDetSpec(
  model_name='efficientdet-lite2',
  uri='https://tfhub.dev/tensorflow/efficientdet/lite2/feature-vector/1',
  model_dir='/content/checkpoints',
  hparams={'max_instances_per_image': 8000})

# Train only the head of the model
model = object_detector.create(train_data, model_spec=spec, batch_size=1, train_whole_model=False, epochs=10, validation_data=val_data)

# Save the partially trained model for later stages
model.export(export_dir='/content/checkpoints', export_format=ExportFormat.SAVED_MODEL, saved_model_filename='partially_trained_model')

